spring:
      
  datasource:
    ### local-b2b(P6SpyDriver)
    url              : jdbc:p6spy:postgresql://localhost:5432/demo
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username         : stoneberg
    password         : new1234@

    hikari:
      connection-timeout: 60000
      minimum-idle      : 3
      maximum-pool-size : 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 500
      hibernate.jdbc.lob.non_contextual_creation: true

  jackson:
    serialization:
      fail-on-empty-beans: false


cos:
  key: cos1234